# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x07\n\x05\x45mpty\"\x1c\n\x07Payload\x12\x11\n\tsensor_id\x18\x01 \x01(\t28\n\rHealthService\x12\'\n\x0bhealthcheck\x12\x0c.api.Payload\x1a\n.api.EmptyB\tZ\x07./apipbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./apipb'
  _EMPTY._serialized_start=18
  _EMPTY._serialized_end=25
  _PAYLOAD._serialized_start=27
  _PAYLOAD._serialized_end=55
  _HEALTHSERVICE._serialized_start=57
  _HEALTHSERVICE._serialized_end=113
# @@protoc_insertion_point(module_scope)
